### ISSUE TITLE
Trying to Integrate xio API Onto Custom Embedded Board

### ISSUE THREAD

**Issue by Legohead259** [xioTechnologies/x-IMU3-Software#193]
I have been trying to integrate the IMU API onto my custom board and am having trouble getting the data to show up in the GUI. My implementation writes the "Euler angles message" to the serial port at 20 Hz. The angles are computed from the Fusion library and are good. Below is a sample of the output information:

```
A,1075887198,-0.0458,2.5299,-124.4267
A,1075941199,-0.0470,2.4980,-124.6745
A,1075995199,-0.0449,2.4367,-124.9043
A,1076049199,-0.0435,2.3313,-125.1606
A,1076103199,-0.0460,2.2200,-125.3819
A,1076157199,-0.0500,2.0731,-125.5776
A,1076211199,-0.0540,1.9971,-125.7597
A,1076265199,-0.0547,1.9035,-125.9520
A,1076319199,-0.0610,1.7915,-126.1387
A,1076378183,-0.0665,1.6960,-126.3233
A,1076432199,-0.0700,1.6098,-126.4728
A,1076486199,-0.0681,1.5323,-126.6172
A,1076540199,-0.0690,1.4572,-126.8056
A,1076594199,-0.0731,1.3591,-126.9686
A,1076648199,-0.0755,1.2729,-127.0300
A,1076702199,-0.0840,1.1683,-127.1952
A,1076756199,-0.0879,1.0820,-127.2724
A,1076810199,-0.0886,1.0126,-127.3917
A,1076864199,-0.0942,0.9440,-127.5378
```

Note that each line is followed with `\r\n`, it is just not displayed in the terminal output.

Is there an implementation issue on my end, or does the GUI require a handshake before it can start displaying data?

**Comment by xioTechnologies** [comment]
No handshaking is required.  The stream you have shown is all that is needed for the x-IMU3 GUI to receive Euler angle messages.  If your stream is not working then I expect there is an issue with the `\r\n`.

**Comment by Legohead259** [comment]
Interesting. I also tried with the `ping` command. The command and response as captured by CoolTerm as follows:
```
{"ping":"\0"}
{"ping":{"interface":"USB","deviceName":"Thetis-F5","serialNumber":"001"}}
```

I verified the hex values of the characters in the terminal and they align with the specified message ESC character.

**Comment by Legohead259** [comment]
For the interface on the GUI is it using 8 data bits, no parity, and 1 stop bit by default?

**Comment by xioTechnologies** [comment]
> is it using 8 data bits, no parity, and 1 stop bit by default

Yes

I think you may have misunderstood how the ping works.  The GUI will send `{"ping":null}` to the device during _Searching For Connections_, and the device would respond with `{"ping":{"interface":"USB","deviceName":"Thetis-F5","serialNumber":"001"}}`.  You may want to replace `"USB"` with `"Serial"` if that is more accurate for your device.

`null `is a JSON keyword.  `"\0"` is invalid JSON because `0` cannot follow the escape character `\` in a JSON string.  You seem to be mixing C and JSON.  JSON is easy to understand and has [beautiful documentation](https://www.json.org/json-en.html).

**Comment by Legohead259** [comment]
Ah. Gotcha. I'll keep that in mind. Issue still stands though that the GUI
is not communicating with my board 🤷‍♂️

I'll keep trying with it tomorrow.

**Comment by xioTechnologies** [comment]
I have tested the x-IMU3 GUI and found no issue.  The following screenshot shows the working serial stream logged using [Tera Term](https://ttssh2.osdn.jp/index.html.en) and then opened in [Notepad++](https://notepad-plus-plus.org/) with _Show All Characters_ enabled to confirm the `\r\n` termination.  I suggest you confirm your termination in a similar way.

![image](https://github.com/xioTechnologies/x-IMU3-Software/assets/1748389/b486ecb7-2ea6-4688-b506-c93eda03513b)

**Comment by Legohead259** [comment]
My results from testing just now. Same process you described.
![image](https://github.com/xioTechnologies/x-IMU3-Software/assets/8077426/a967e769-194a-4c7e-8af7-263952e6b54a)

**Comment by xioTechnologies** [comment]
I do not see a issue with those ASCII lines.  Please can you log several seconds of that stream using [Tera Term](https://ttssh2.osdn.jp/index.html.en) and share the file with me.

**Comment by Legohead259** [comment]
> I do not see a issue with those ASCII lines. Please can you log several seconds of that stream using [Tera Term](https://ttssh2.osdn.jp/index.html.en) and share the file with me.

See attached. Thanks for looking into this.
[thetis_log.txt](https://github.com/xioTechnologies/x-IMU3-Software/files/11525197/thetis_log.txt)

**Comment by xioTechnologies** [comment]
Is your device using RTS/CTS hardware flow control?  The current release ([v1.1.4](https://github.com/xioTechnologies/x-IMU3-Software/releases/tag/v1.1.4)) permanently asserts RTS and so would inhibit device transmission.  This was fixed in 8d883ae64165503d35927222f337e75b3a685c7b but will not be available until the next release.  Until then, you should not use RTS/CTS hardware flow control.

**Comment by Legohead259** [comment]
I GOT IT!!!!!

I had to monitor the COM ports on my computer using a virtual serial port driver. That showed me that as soon as the GUI opened and started talking with the device, it stopped transmitting, hence our problem! I fixed it by continually flushing the Serial input buffer to the device. It seems that when that buffer is full, it crashes the device.

![image](https://github.com/xioTechnologies/x-IMU3-Software/assets/8077426/bab593e0-23b9-4006-8413-971338f881e4)

**Comment by Legohead259** [comment]
In a future update, could you add a serial port monitor or something into the GUI that spits out all of the traffic into a window? That would have made this easier and more streamlined.

**Comment by Legohead259** [comment]
I noticed that. But I mean like an actual serial port monitor where the data is written directly to the window. That would help in cases where the messages may not be properly parsed, but still being sent. Vice versa, it could also help figure out what messages are being sent from the GUI to a device.

**Comment by xioTechnologies** [comment]
Thank you for the suggestion.  I do not believe there is a strong use case for such a feature given the challenges and issues it would introduce, and given that there are already far more power and convenient tools available for debugging serial and socket streams.

In cases where messages may not be properly parsed, the connection will generate a [decode error](https://github.com/xioTechnologies/x-IMU3-Software/blob/main/x-IMU3-API/Rust/src/decode_error.rs).  This is demonstrated in the [examples](https://github.com/xioTechnologies/x-IMU3-Software/tree/main/Examples) and is on the GUI feature roadmap.

**Comment by Legohead259** [comment]
Fair enough. Thanks for the help looking into this issue through the past couple of days. Closing this now.

**Comment by Legohead259** [comment]
Leaving this here for future Braidan.

Steps to get x-IMU3 GUI to work with Thetis as of 06/02/2023:
1. Create two split virtual COM ports from the real COM port using Virtual Serial Port Driver Pro (or similar)
2. Connect Tera Term to the main virtual COM port
3. Connect the GUI to the secondary virtual COM port
4. Profit.

Unfortunately, as of right now the GUI cannot talk directly with Thetis, it needs this medium of virtual COM ports. I believe it has something to do with the USB handshake? I'm not entirely certain right now.

**Comment by xioTechnologies** [comment]
Please can you test if the issue is solved with the latest x-IMU3 GUI release, [v1.2.0](https://github.com/xioTechnologies/x-IMU3-Software/releases/tag/v1.2.0).

**Comment by Legohead259** [comment]
> Please can you test if the issue is solved with the latest x-IMU3 GUI release, [v1.2.0](https://github.com/xioTechnologies/x-IMU3-Software/releases/tag/v1.2.0).

It absolutely works! That's awesome. What changes did you make to the serial interface that could have fixed it?
![image](https://github.com/xioTechnologies/x-IMU3-Software/assets/8077426/c328f5a7-80a8-40d3-b92f-f7729f6a9c50)

**Comment by xioTechnologies** [comment]
I believe the issue is as a [described above](https://github.com/xioTechnologies/x-IMU3-Software/issues/193#issuecomment-1559840733).  My previous comment was mistaken in that it is the DTR line that is permanently asserted, not the RTS.  I believe you are using an ESP32 with a USB-UART converter that uses the DTR line to control the ESP32 reset/boot signals.  Your hardware would therefore be held in reset whenever the x-IMU3 Software opens the serial port.

**Comment by xioTechnologies** [comment]
I notice that your 3D model has no colour.  If you want to include colour then you should provide an `.mtl` file in the same location, and with the same name as the `.obj` file.  I have added [instructions](https://github.com/xioTechnologies/x-IMU3-Software/tree/main/x-IMU3-GUI/Source/OpenGL/Assets#readme) for generating these files.
