### ISSUE TITLE
Arduino-compatible library for xioAPI

### ISSUE THREAD

**Issue by Legohead259** [xioTechnologies/x-IMU3-Software#195]
As I've been working on integrating the xioAPI onto my custom board, I have forked a repository from [Reefwing](https://github.com/Reefwing-Software/Reefwing-xIMU3). But their library is limited and relies on their common hardware libraries. 

I'd like to develop a general library that can be deployed onto Arduino-compatible microcontrollers. Would it be possible for you to release the files you use for the x-IMU3 and its API implementation? Else, help me develop a generalized library. My current effort can be found in the [ThetisAPI repo](https://github.com/Legohead259/ThetisAPI).

My end goal is to develop a package that can be downloaded onto Arduinos with IMUs and be instantly compatible with the x-IMU GUI.

**Comment by xioTechnologies** [comment]
Thank you for the suggestion and your initial work towards this goal.  I look forward to discussing this further in our scheduled call.
