### ISSUE TITLE
trying to install the development setup

### ISSUE THREAD

**Issue by DanielSamp4** [xioTechnologies/x-IMU3-Software#231]
You can help me to understand, why i'm getting this error mensagens when i try to run this repo? i have made everything that was indicate on Development Setup section.

```error
[149/229] Linking CXX executable Examples\Cpp\Cpp-Examples.exe
FAILED: Examples/Cpp/Cpp-Examples.exe 
cmd.exe /C "cd . && C:\PROGRA~1\JETBRA~1\CLION2~1.3\bin\mingw\bin\G__~1.EXE -g  Examples/Cpp/CMakeFiles/Cpp-Examples.dir/main.cpp.obj -o Examples\Cpp\Cpp-Examples.exe -Wl,--out-implib,Examples\Cpp\libCpp-Examples.dll.a -Wl,--major-image-version,0,--minor-image-version,0  C:/Users/danig/Documents/GitHub/x-IMU3-Software/x-IMU3-API/Rust/target/release/ximu3.lib  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 && cd ."
Warning: corrupt .drectve at end of def file
C:\Program Files\JetBrains\CLion 2023.1.3\bin\mingw\bin/ld.exe: Examples/Cpp/CMakeFiles/Cpp-Examples.dir/main.cpp.obj: in function `ximu3::DataLogger::getResult()':
C:/Users/danig/Documents/GitHub/x-IMU3-Software/x-IMU3-API/Cpp/DataLogger.hpp:25: undefined reference to `XIMU3_data_logger_get_result'
C:\Program Files\JetBrains\CLion 2023.1.3\bin\mingw\bin/ld.exe: Examples/Cpp/CMakeFiles/Cpp-Examples.dir/main.cpp.obj: in function `ximu3::NetworkAnnouncement::getResult()':
C:/Users/danig/Documents/GitHub/x-IMU3-Software/x-IMU3-API/Cpp/NetworkAnnouncement.hpp:26: undefined reference to `XIMU3_network_announcement_get_result'
C:\Program Files\JetBrains\CLion 2023.1.3\bin\mingw\bin/ld.exe: C:/Users/danig/Documents/GitHub/x-IMU3-Software/x-IMU3-API/Rust/target/release/ximu3.lib(ximu3-9d51039fde32745d.ximu3.0eefa5cf-cgu.6.rcgu.o):ximu3.0eefa5cf-cgu:(.xdata[$cppxdata$_ZN107_$LT$alloc..boxed..Box$LT$$u5b$I$u5d$$GT$$u20$as$u20$core..iter..traits..collect..FromIterator$LT$I$GT$$GT$9from_iter17he6755c612336f861E]+0x2c): undefined reference to `__CxxFrameHandler3'
C:\Program Files\JetBrains\CLion 2023.1.3\bin\mingw\bin/ld.exe: C:/Users/danig/Documents/GitHub/x-IMU3-Software/x-IMU3-API/Rust/target/release/ximu3.lib(ximu3-9d51039fde32745d.ximu3.0eefa5cf-cgu.6.rcgu.o):ximu3.0eefa5cf-cgu:(.xdata[$cppxdata$_ZN17crossbeam_channel7channel15Sender$LT$T$GT$4send17h1836224e2fcb7d55E]+0x10): undefined reference to `__CxxFrameHandler3'
C:\Program Files\JetBrains\CLion 2023.1.3\bin\mingw\bin/ld.exe: C:/Users/danig/Documents/GitHub/x-IMU3-Software/x-IMU3-API/Rust/target/release/ximu3.lib(ximu3-9d51039fde32745d.ximu3.0eefa5cf-cgu.6.rcgu.o):ximu3.0eefa5cf-cgu:(.xdata[$cppxdata$_ZN17crossbeam_channel7channel15Sender$LT$T$GT$4send17h62e50a5a41aefd23E]+0x14): undefined reference to `__CxxFrameHandler3'
```

**Comment by xioTechnologies** [comment]
I expect the issue is that you are using the latest master branch with the static library of the most recent release ([v1.1.4](https://github.com/xioTechnologies/x-IMU3-Software/releases/tag/v1.1.4)).  The master branch is currently ahead of the release.  You need to either...

1. build the static library for the latest master branch yourself, or...
2. checkout the master branch at the most recent release.

**Comment by DanielSamp4** [comment]
When u say "build the static library for the latest master branch yourself", are u saying that i have to run cmake .  o the root directory ? because i have already did that and when all have finished and i try to build the same error message was prompt again
Sorry i kind of nub yet, so if u could detail more the step that i have to make to get the static library rebuild i will appreciate

**Comment by xioTechnologies** [comment]
The static library is the `C:/Users/danig/Documents/GitHub/x-IMU3-Software/x-IMU3-API/Rust/target/release/ximu3.lib` in the compiler error you shared.  I assumed that you copied this file from the [v1.1.4 release](https://github.com/xioTechnologies/x-IMU3-Software/releases/tag/v1.1.4) assets as [instructed](https://github.com/xioTechnologies/x-IMU3-Software/blob/main/x-IMU3-API/Rust/target/release/README.md) by the following warning message, displayed when you run the [root CMake](https://github.com/xioTechnologies/x-IMU3-Software/blob/main/CMakeLists.txt) for the first time.
```
CMake Warning at CMakeLists.txt:20 (message):
  Please provide the missing library file and then reload the CMake project.
  https://github.com/xioTechnologies/x-IMU3-Software/blob/main/x-IMU3-API/Rust/target/release/README.md
```
If this is what you did then the issue would be that the master branch is ahead of the release, and includes calls to functions that do not exist in the static library.  Hence the linker errors.  The solution would be to checkout the master branch at the commit corresponding to the release.

If you wish to instead build the library yourself then you must compile the Rust-API and then reload the CMake as per the instructions.  The Rust-API is separate from CMake.  We build it by clicking _Build_ in CLion, but you can also build from the command line by running `cargo build --release` in the [Rust directory](https://github.com/xioTechnologies/x-IMU3-Software/tree/main/x-IMU3-API/Rust).

**Comment by DanielSamp4** [comment]
Thanks for the help, rebuilding the ximu3 library made it possible to run the GUI, and now I have the executable running fine, I'll start to make changes to try to implement the movement for the 3d object
