### ISSUE TITLE
Feature Request: Maintain display of custom 3D model between window reloads

### ISSUE THREAD

**Issue by Legohead259** [xioTechnologies/x-IMU3-Software#236]
it would be nice to choose the default 3D model that is displayed when the GUI window is opened.
Alternatively, if we could load a custom 3D model based on the device name/serial number that would also be awesome

**Comment by xioTechnologies** [comment]
I believe that the generalised feature of _graphs and 3D view remembering their state_ would provide the behaviour you are looking for.  We will look into this.

**Comment by Legohead259** [comment]
Yep, that's a better way to phrase it :)

**Comment by xioTechnologies** [comment]
This feature is now available in [v1.3.5](https://github.com/xioTechnologies/x-IMU3-Software/releases/tag/v1.3.5).  The x-IMU3 GUI will restore the window layout, individual graph settings, and 3D view settings.
