### ISSUE TITLE
x-IMU3-GUI can not find device via usb cable on Windows 7

### ISSUE THREAD

**Issue by Allidylls** [xioTechnologies/x-IMU3-Software#290]
I have one x-IMU3 device connecting to a ThinkPad T430 via USB cable, but the GUI app couldn't find it. 
Is there a device driver?  Any information would be appreciated.

![cap3](https://github.com/xioTechnologies/x-IMU3-Software/assets/1175717/6ff7384b-0351-49a6-a0fd-074af505869e)

![cap2](https://github.com/xioTechnologies/x-IMU3-Software/assets/1175717/3bce80cc-991a-49a0-b3c8-85ac376bf4dc)

![cap1](https://github.com/xioTechnologies/x-IMU3-Software/assets/1175717/35bd8120-b3c0-4184-b4e2-cd8839b8e05f)

**Comment by xioTechnologies** [comment]
USB drivers are not required by the x-IMU3 for most operating systems but Windows 7 is very old (14 years).  We have a Windows 7 machine here and are testing a solution for you.  I will update you shortly.

**Comment by Allidylls** [comment]
Yes, My OS is too old. I have tried several USB 3.0 drivers, but still cannot connect the sensor. At last, I upgrade the win7 to win10, then, it works. Thank you.
