### ISSUE TITLE
Contribution, Licensing and Usage Policy

### ISSUE THREAD

**Issue by RDCH106** [xioTechnologies/x-IMU3-Software#379]
Hello Team,

First of all, congratulations on your great project.

I am confused with the licensing because the main project is GPL-3. But at the same time, the API code for the sensor connection is distributed in PyPI for Python and Crates for Rust with MIT. In both platforms, the code reference is pointing to this repository.

I assume the code of the Python package published in PyPI is: https://github.com/xioTechnologies/x-IMU3-Software/tree/main/x-IMU3-API/Python

The code of the Rust package published in Crates is: https://github.com/xioTechnologies/x-IMU3-Software/tree/main/x-IMU3-API/Rust

While the [MIT](https://choosealicense.com/licenses/mit/) license allows these packages to be used in third-party developments for Python and Rust, they do not allow the use of the code that is in this repository because it is marked as [GPL-3](https://choosealicense.com/licenses/gpl-2.0/). This circumstance does not allow contributions to be made to the package code, nor to directly use the code of those distributions because all code must be distributed with the GPL-3 due to this license. Is this what is expected?

This situation does not allow, for example, to include the package in [vcpkg](https://github.com/microsoft/vcpkg) to be distributed as is the case with Python and Rust. I could collaborate on this if the license was correct because I cannot legally re-license part of a GPL-3 repository to be MIT in its distribution.

Maybe what you want is to protect general apps with GPL-3, but then you want to facilitate the use of sensors by publishing MIT-licensed packages in different languages, as seems to be the case in this repository path:

- https://github.com/xioTechnologies/x-IMU3-Software/tree/main/x-IMU3-API

In this case, the normal thing is to generate a repository with its own MIT license for each connector in each language and then include them in the repository as Git submodules. This also makes code reusability much easier.

If this is too much trouble it is also possible to enter licenses in the subdirectories, but this is less clear and would require an explanatory note somewhere.

All these comments have no other objective than to maximize collaboration and use of the project while respecting the license agreement, which must be clear.

ℹ️ More info about software licenses and each clause: https://choosealicense.com/appendix/

**Comment by xioTechnologies** [comment]
Thank you for raising this issue.  Our intention is to use MIT for everything except the [x-IMU3-GUI](https://github.com/xioTechnologies/x-IMU3-Software/tree/main/x-IMU3-GUI) directory and below.  The x-IMU3 GUI uses [JUCE](https://juce.com/) as _JUCE Personal Free_ and so must be distributed under GNU GPLv3 as per cause 1.9 of the [JUCE licence](https://juce.com/legal/juce-7-license/).

We decided against submodules because of the significant interdependency between the APIs, GUI, and various language examples.  Use of submodules would mean each API update potentially triggering a cascade of ten other releases; each with it's own versioning and interconnected CI processes.

It sounds like the simplest solution would be for us to purchase a JUCE commercial licence and eliminate the clause 1.9 requirement.  We can then continue to distribute open-source voluntarily but do so under a licence of our choosing.  The whole repository would then become MIT with a single licence file in the root.  Does this sound like an appropriate solution to you?

**Comment by RDCH106** [comment]
It may be a solution. If you consider it correct for you, there is no problem. For possible synergies in Open Source with all its technical benefits, the repository should display the MIT License:

![imagen](https://github.com/xioTechnologies/x-IMU3-Software/assets/1483414/576e61b9-f728-4ac8-b3d3-05faa8820824)

Currently, the project is more Free Software than Open Source due to the type of license chosen.

**Comment by xioTechnologies** [comment]
Thank you.  I will discuss with the team and likely make the change at the end of the week.  I will update this issue then.

**Comment by xioTechnologies** [comment]
We have included separated licence files added a [licence section](https://github.com/xioTechnologies/x-IMU3-Software/blob/main/README.md#licence) to the README that should clarify things.

**Comment by RDCH106** [comment]
Thank you for the license change!

The MIT license lets work with convenient coverture for the contributions, usage, and licensing.

**Comment by RDCH106** [comment]
Another question...

For some reason, the git tree has been rewritten since commit [8476c22b911254ee12874c01719f9308a9cac059](https://github.com/xioTechnologies/x-IMU3-Software/commit/8476c22b911254ee12874c01719f9308a9cac059) ?

Many of the commits appear to be maintained but do not have the same hash in the commit. It isn't easy to work on a repository that rewrites its main branch, which should be stable.

My fresh clone of the repository the last 2024/02/26:

![imagen](https://github.com/xioTechnologies/x-IMU3-Software/assets/1483414/2f0e3813-f1f3-4971-9918-5bec0b03ad4d)

The repository fetching the changes today 2024/03/04:

![imagen](https://github.com/xioTechnologies/x-IMU3-Software/assets/1483414/14c97051-00d6-4a03-b560-83f896adfd20)

**Comment by xioTechnologies** [comment]
The main branch from the last release ([v1.3.10](https://github.com/xioTechnologies/x-IMU3-Software/releases/tag/v1.3.10)) was force pushed for tidying.  It is very rare that the main branch will be modified in this way.  The main branch is guaranteed to be stable up to each release.  I recommend that you only branch from releases (i.e. tagged commits), regardless of main branch stability.

**Comment by xioTechnologies** [comment]
I believe the main branch has only be overwritten 2-3 times in this repositories 2 year history.  Your comments have been taken onboard and this will be avoided in future.  However, it is still recommended that you only work with releases.
