### ISSUE TITLE
appropriate Python tool/method to integrate IMU data with my existing code 

### ISSUE THREAD

**Issue by camillaBobo** [xioTechnologies/x-IMU3-Software#419]
I am implementing an algorithm for object pose estimation, where position is estimated by a camera+Tag system, and orientation is fused using the camera+Tag and IMU orientation reading. 
I already have the python code for computing position and orientation through a camera + Tag system , as well as the sensor fusing algorithm. 
My question is about the best approach to integrate IMU data reading into my existing setup for object pose estimation.
One idea is to send out the orientation through sockets, and use a different python file to read the real-time data, but I am encountering some issues. Not sure what the best approach is.
Any suggestions would be appreciated! Thanks!

**Comment by xioTechnologies** [comment]
I'm struggling to understand this post.  Did you mean to post in this repository?  Are you using an [x-IMU3](https://x-io.co.uk/x-imu3/) or the [x-IMU3 Software](https://github.com/xioTechnologies/x-IMU3-Software)?

**Comment by camillaBobo** [comment]
I am using both x-imu3 sensor and the software. I wasn't sure what the best way to integrate the sensor reading to my existing python framework. But I just found using threading and maintaining a few global variables is a good option for me.
Thank you for getting back to me, and if you have other suggestions, please let me know.
